feat(brimstone): Response to GitGuardian events with metadata
conjurdemos/cyberark-gitguardian-hmsl-remediation-integration-service pull request #9
Opened 2024-05-16 08:25 UTC by Walz

The goal of this PR is to respond to the webhook with metadata on the affected accounts. This will enable GitGuardian to display information about Brimstone's actions.

```json
[
    {
        "name": "example_name",
        "present": true,
        "rotated": false,
        "added": false,
        "safe_name": "example_pending"
    }
]
```

2024-05-23 08:17 UTC, Walz commented
Hello @davidh-cyberark, could you please review this PR? Thank you.

2024-05-29 14:33 UTC, davidh-cyberark commented on pkg/brimstone/brimstone.go
>  // FindAccountID - given hmslhash return list of accountids from the db
please update the function comment to reflect the changes made

2024-05-29 14:44 UTC, davidh-cyberark commented
@Walz first pass is done.  please review and update.

2024-05-30 14:19 UTC, Walz commented
Thanks for the review, I've updated the function comment to reflect the change.

2024-06-04 15:23 UTC, davidh-cyberark requested changes

2024-06-04 15:23 UTC, davidh-cyberark commented on pkg/brimstone/brimstone.go
> +	db.Where(&SafeHash{Hash: hmslhash}).Find(&hashes)
check for failure and return error if there was an error

2024-06-04 15:23 UTC, davidh-cyberark commented on pkg/brimstone/brimstone.go
> +			accountMetadata.Added = true
Please add a comment here explaining what this is used for.

I'm assuming this is used by GG.  For visibililty it would help to know what this is affecting on the GG side.

2024-06-04 15:23 UTC, davidh-cyberark commented on pkg/brimstone/brimstone.go
> +// FindAccount - given hmslhash return list of accounts from the db
This is incongruent.   "FindAccounts" (plural) would be congruent with the implementation.  Please rename the function to the plural form.

2024-06-06 17:20 UTC, Walz commented on pkg/brimstone/brimstone.go
> +			accountMetadata.Added = true
I've added a comment above the declaration of `AccountMetadata` and before the final return of `GitGuardianEventPost`.

2024-06-06 17:20 UTC, Walz commented on pkg/brimstone/brimstone.go
> +// FindAccount - given hmslhash return list of accounts from the db
I've updated the name

2024-06-06 18:25 UTC, davidh-cyberark commented
Looks ready for merging, except need to bump the version.

Please bump the version.  "make versionbump"

2024-06-07 08:23 UTC, Walz commented
Thanks for the review, I've added a commit to bump the version.

2024-06-07 17:50 UTC, merged